module.exports = {
  name: 'default',
  type: 'postgres',
  host: process.env.TYPEORM_DB_HOST,
  port: Number(process.env.TYPEORM_DB_PORT),
  username: process.env.TYPEORM_DB_USER_NAME,
  password: process.env.TYPEORM_DB_USER_PASS,
  database: 'test',
  dropSchema: true,
  logging: false,
  synchronize: true,
  migrationsRun: true,
  entities: [__dirname + '/**/*.entity{.ts,.js}'],
  migrations: [__dirname + '/migrations/*{.ts,.js}'],
};
